package StateMachine.sandbox.SM;

/*Generated by MPS */


public class MachineStateMachine {
  private MachineStateMachine.EStates state = 
  B();

  public void step(Integer token) {
    switch (state) {
      case 
      A():
        if (23) {
          state = <!TextGen not found for 'StateMachine.structure.Transition'!>;
        }
        break;
      case 
      B():
        break;
      default:
    }
  }

  public static   enum EStates {
    A(),
    B();

    EStates() {
    }
  }
}
