package StateMachine.sandbox.SM;

/*Generated by MPS */


public class Main {
  public static boolean testMultipleOf5(String in) {
    MultipleOf5StateMachine machine = new MultipleOf5StateMachine();
    for (int i = 0; i < in.length(); i++) {
      machine.step(in.charAt(i));
    }
    return machine.getState().isFinal();
  }

  public static void main(String[] args) {
    String[] test = {"0", "1", "101", "1010", "1011", "1111"};
    for (String in : test) {
      String res = (testMultipleOf5(in) ?
        "" :
        "NOT "
      );
      System.out.println(in + " is " + res + "multiple of 5");
    }
  }
}
