package StateMachine.sandbox.SM;

/*Generated by MPS */


public class MultipleOf5StateMachine {
  private MultipleOf5StateMachine.EState state = MultipleOf5StateMachine.EState.St_Start;

  public void step(Character token) {
    switch (state) {
      case St_Start:
        if (token == '1') {
          state = MultipleOf5StateMachine.EState.St_1;
        }
        break;
      case St_1:
        if (token == '0') {
          state = MultipleOf5StateMachine.EState.St_2;
        }
        if (token == '1') {
          state = MultipleOf5StateMachine.EState.St_3;
        }
        break;
      case St_2:
        if (token == '0') {
          state = MultipleOf5StateMachine.EState.St_4;
        }
        if (token == '1') {
          state = MultipleOf5StateMachine.EState.St_5;
        }
        break;
      case St_3:
        if (token == '0') {
          state = MultipleOf5StateMachine.EState.St_1;
        }
        if (token == '1') {
          state = MultipleOf5StateMachine.EState.St_2;
        }
        break;
      case St_4:
        if (token == '0') {
          state = MultipleOf5StateMachine.EState.St_3;
        }
        if (token == '1') {
          state = MultipleOf5StateMachine.EState.St_4;
        }
        break;
      case St_5:
        if (token == '1') {
          state = MultipleOf5StateMachine.EState.St_1;
        }
        break;
      default:
    }
  }

  public MultipleOf5StateMachine.EState getState() {
    return state;
  }

  public static   enum EState {
    St_Start(false),
    St_1(false),
    St_2(true),
    St_3(false),
    St_4(false),
    St_5(true);

    private final boolean isFinal;

    EState(boolean isFinal) {
      this.isFinal = isFinal;
    }

    public boolean isFinal() {
      return isFinal;
    }
  }
}
