package StateMachine.behavior;

/*Generated by MPS */


public class StateMachineOperation_getState_BehaviorDescriptor extends StateMachineOperation_BehaviorDescriptor {
  public StateMachineOperation_getState_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StateMachine.structure.StateMachineOperation_getState";
  }
}
