package StateMachine.behavior;

/*Generated by MPS */


public class StateMachineOperation_step_BehaviorDescriptor extends StateMachineOperation_BehaviorDescriptor {
  public StateMachineOperation_step_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StateMachine.structure.StateMachineOperation_step";
  }
}
