package StateMachine.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Type_BehaviorDescriptor;

public class StateMachineType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public StateMachineType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "StateMachine.structure.StateMachineType";
  }
}
