package StateMachine.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.CompiledConceptDescriptor;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  private static String[] stringSwitchCases_1htk8d_a0a0a = new String[]{"StateMachine.structure.State", "StateMachine.structure.StateMachine", "StateMachine.structure.StateMachineCreator", "StateMachine.structure.StateMachineOperation", "StateMachine.structure.StateMachineOperation_getState", "StateMachine.structure.StateMachineOperation_step", "StateMachine.structure.StateMachineType", "StateMachine.structure.StateOperation_isFinal", "StateMachine.structure.Transition"};

  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0a, conceptFqName)) {
      case 0:
        return new CompiledConceptDescriptor("StateMachine.structure.State", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept"}, new String[]{"final"}, new String[]{});
      case 1:
        return new CompiledConceptDescriptor("StateMachine.structure.StateMachine", "jetbrains.mps.baseLanguage.structure.Type", false, new String[]{"jetbrains.mps.baseLanguage.structure.Type", "jetbrains.mps.lang.core.structure.INamedConcept"}, new String[]{}, new String[]{"initialState"});
      case 2:
        return new CompiledConceptDescriptor("StateMachine.structure.StateMachineCreator", "jetbrains.mps.baseLanguage.structure.AbstractCreator", false, new String[]{"jetbrains.mps.baseLanguage.structure.AbstractCreator"}, new String[]{}, new String[]{"stateMachine"});
      case 3:
        return new CompiledConceptDescriptor("StateMachine.structure.StateMachineOperation", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.baseLanguage.structure.IOperation"}, new String[]{}, new String[]{});
      case 4:
        return new CompiledConceptDescriptor("StateMachine.structure.StateMachineOperation_getState", "StateMachine.structure.StateMachineOperation", false, new String[]{"StateMachine.structure.StateMachineOperation"}, new String[]{}, new String[]{});
      case 5:
        return new CompiledConceptDescriptor("StateMachine.structure.StateMachineOperation_step", "StateMachine.structure.StateMachineOperation", false, new String[]{"StateMachine.structure.StateMachineOperation"}, new String[]{}, new String[]{});
      case 6:
        return new CompiledConceptDescriptor("StateMachine.structure.StateMachineType", "jetbrains.mps.baseLanguage.structure.Type", false, new String[]{"jetbrains.mps.baseLanguage.structure.Type"}, new String[]{}, new String[]{"stateMachine"});
      case 7:
        return new CompiledConceptDescriptor("StateMachine.structure.StateOperation_isFinal", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.baseLanguage.structure.IOperation"}, new String[]{}, new String[]{});
      case 8:
        return new CompiledConceptDescriptor("StateMachine.structure.Transition", "jetbrains.mps.lang.core.structure.BaseConcept", false, new String[]{"jetbrains.mps.lang.core.structure.BaseConcept"}, new String[]{}, new String[]{"to"});
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }
}
